### ISSUE TITLE
Reconsider the name of the `annotations` folder and its contents

### ISSUE THREAD

**Issue by marcelm** [frisen-lab/TREX#12]

**Comment by marcelm** [comment]
I’ve moved this to-do item to a separate issue so the discussion can be kept separate.

The folder name `annotations/` isn’t quite accurate. I chose it only because I had to come up with something quickly: The `H2b-EGFP-30N-LTR.fa` file in it isn’t annotation. The commonality between the two files is that they are needed to reproduce the results from the paper, so a name reflecting that may be better. (I still cannot come up with anything better, though ...)

You said that all available annotations should be moved to that folder. Which ones would these be? We have the `chrTomato-N.fa` and `chrTomato-N.gtf` files, but are these relevant for anyone?

**Comment by Leonievb** [comment]
Yes, these files are relevant for those who want to follow up each step of the test including merging the extra chromosome into the reference genome with cellranger mkref. So what about calling this folder `references`?

**Comment by marcelm** [comment]
Perfect! I have renamed the folder now and copied the `chrTomato*` files into it. 

Do we need the `chrTomato*` files in `tests/data/` at all? The tests run without them. But having copies would be ok in this limited case.

**Comment by Leonievb** [comment]
no, we actually don't need it there at all. Whoever is interested in learning how to prepare for the cellranger run, will not look into this folder to find the references

**Comment by marcelm** [comment]
Good, I will move the files instead of copying them.
