### ISSUE TITLE
Raw umi matrix?

### ISSUE THREAD

**Issue by cnk113** [frisen-lab/TREX#19]
Hello,

I've been looking at the umi matrix of the clonal barcodes outputted from trex run10x on your nature neuro paper. I turn off filter cells and turn on keep single reads. However the output matrix is still filtered... Is there an issue with those parameters? I'm looking to get the most raw umi matrix (including non-called cells). 

Best,
Chang

**Comment by marcelm** [comment]
The `umi_count_matrix.csv` does not contain raw UMI counts. The file just presents the data in the `cells_filtered.txt` file in a different way. To get unfiltered cells, you could use `cells.txt`, but that file does not give you the data as a matrix, so you would need to reformat it, and it is perhaps still not as raw as you want it.
