### ISSUE TITLE
Remove and flag doublets

### ISSUE THREAD

**Issue by marcelm** [frisen-lab/TREX#30]
@acorbat pointed out today that they have observed undesirable clustering results arising from doublets. In the clone graph, these should manifest themselves as vertices that are part of two clusters at the same time.

We can possibly find these by looking for [cut vertices](https://en.wikipedia.org/wiki/Biconnected_component) in the graph. A cut vertex is a vertex whose removal would lead to an increase in the number of connected components. There exist fast algorithms to find cut vertices.

(Note the similarity to bridges: A bridge is an edge whose removal would lead to an increase in the no. of connected components.)

**Comment by marcelm** [comment]
Here is an example doublet that I manually marked in the test data you sent:

![image](https://github.com/frisen-lab/TREX/assets/724864/31229843-e274-452d-b81f-c481888814d6)

(Created by editing the `graph_corrected.pdf` file that `trex run10x --plot` creates.)

**Comment by acorbat** [comment]
We should save a list of the flagged or removed doublets as they should also be removed from the original dataset.

**Comment by acorbat** [comment]
@marcelm Can we close this one?

**Comment by marcelm** [comment]
Yes!
