### ISSUE TITLE
Feature: Having Quality Control plots after running TREX

### ISSUE THREAD

**Issue by acorbat** [frisen-lab/TREX#32]
It would useful to have quality control plots after running TREX. The rationale is that changing parameters for different runs yield different results and it would be useful to have an overview of how well the different steps worked and what the end point as well as intermediate points were.

**Comment by marcelm** [comment]
Hi, just wanted to mention that I think it’s totally fine *not* to open an issue if you plan to submit a PR solving the issue at the same time.

Some projects have it as a policy that everything needs to be tracked as an issue (that is, every nontrivial PR needs to close an existing issue), which I kind of understand for larger projects, but I suggest to keep it simple for a small project like this.
