### ISSUE TITLE
Folder structure is inconsistent

### ISSUE THREAD

**Issue by Leonievb** [frisen-lab/TREX#4]
The folder structure of this git repository is inconsistent and confusing. For example,
* [x] #12
* [x] the folder `expected` can be moved to `/tests/expected`
* [x] the file `chrTomato-N.fa` in `/tests/data/outs/` should be moved to `/tests/data/`
* [ ] folder `/tests/data/outs/filtered_gene_bc_matrices` should be renamed to `/tests/data/outs/filtered_feature_bc_matrices`
* [ ] The files `barcodes.tsv`, `genes.tsv` and `matrix.mtx` in `/tests/data/outs/filtered_gene_bc_matrices)/hg38_Tomato-N/` are expected to be compressed (e.g. `barcodes.tsv.gz` by the algorithm and algorithm gives error if not

**Comment by marcelm** [comment]
Regarding compressed `barcodes.tsv.gz`: We need to add a test for this. What exactly gives an error?

**Comment by marcelm** [comment]
We support two CellRanger directory layouts, see https://github.com/frisen-lab/TREX/blob/main/src/trex/cellranger.py.

The CellRanger 2 layout:
- uses `outs/filtered_gene_bc_matrices/`
- uses `barcodes.tsv`

The CellRanger 3 layout:
- uses `outs/filtered_feature_bc_matrix/`
- uses `barcodes.tsv.gz`

We detect the format automatically depending on whether a `filtered_gene_bc_matrices` or `filtered_feature_bc_matrix` subfolder exists in the `outs/` folder.

You wrote `filtered_feature_bc_matrices` ("feature" and plural "matrices"), which is a combination of the two. Is that a typo or is the directory really named that way?

**Comment by Leonievb** [comment]
To your first question: I haven't seen that error myself but I got told by someone using the code that this happened only when trying to run the pipeline on the test data with the -f flag. If required, I can request the person to reproduce the error and send the error message.

**Comment by Leonievb** [comment]
To the second question: This was a typo from my side, I am sorry for confusion! The layouts of CelllRanger 2 and 3 are exactly as you write it. And the person I talked to said she had to rename folders to the CellRanger 3 layout as soon as she used extra arguments. I will ask her to send more details...

**Comment by Leonievb** [comment]
The person reporting issues on folder name and compression of files could not reproduce the error. Therefore I would keep the folder names and files as they are and also close this issue for now
