### ISSUE TITLE
Add a filtering option for excluding certain cloneIDs

### ISSUE THREAD

**Issue by marcelm** [frisen-lab/TREX#40]
As @acorbat reports, some cloneIDs keep recurring across different experiments and are therefore artifacts that should be filtered out.

His feature request: Add an option that lets us provide a list of cloneIDs (complete or incomplete sequences) to be filtered out.

**Comment by acorbat** [comment]
It could happen that during library preparation some specific barcode appears overrepresented in the viral library. This would lead to an increased probability of cells being infected with this barcode, ending in non-unique labelling. A workaround would be to make a black- or whitelist and filter these barcodes.

We made a list of barcodes that appear way too often by looking into which ones appear across several different experiments. 
Amongst these, we found one barcode that appears in every dataset, and is often misaligned (maybe it is some degradation byproduct that has a similar sequence to TdTomato or something). The full sequence of this one is GAAGAAGAGGAAAGTCTAAATGCATGGTAC, but incomplete versions of it also appear and look like -------------GTCTAAATGCATGGTAC, --------GGAAAGTCTAAATGCATGGTAC or 0000000000000000TAAATGCATGGTAC, and more. There are other barcodes that appear in 2 datasets out of 5. This could be random chance or overrepresentation.

Feature: provide a list of barcodes (full or incomplete sequences) that would be filtered and disregarded during the pipeline?

Proposals: 
1. To make this list I looked into barcodes after correction and before making the clones so one option is to add a filtering step in [this line](https://github.com/frisen-lab/TREX/blob/df86afe900257fbbcf8a59e8ce98eb9aa066d76e/src/trex/cli/run10x.py#L230).
2. Another option would be to filter these out from the beginning, while we are removing low complexity barcodes for example. We could compare incomplete sequences to any of the blacklisted ones (using Hamming distance for example). This could be an easy way to deal with the misaligned one.

Do you have any other suggestions or improvements?

For the time being, I will leave out the question on how to get this blacklist. We discussed a couple possibilities like retrieving it from the library characterization or building it from the actual datasets, but I'd rather separate this discussion into a different issue.

**Comment by marcelm** [comment]
I believe this can be closed because #55 was merged.
