### ISSUE TITLE
The output of the clone calling algorithm does not match R output in some cases

### ISSUE THREAD

**Issue by Leonievb** [frisen-lab/TREX#7]
In some cases the clone calling algorithm produces unreasonably big clones clumping together many cells that are split into separate clones by the R algorithm (with same parameters)

**Comment by marcelm** [comment]
To summarize your intense research on this (which you sent me an e-mail about), the output of our clone calling algorithm exactly matches the R output if the Jaccard threshold is set to 0.7 as in R. Our default is 0.0 and, as you also suggest, we should possibly consider changing it to 0.7.
