### ISSUE TITLE
Usage of the smartseq vs. 10x runs commands unclear

### ISSUE THREAD

**Issue by Leonievb** [frisen-lab/TREX#8]
The `run10x` positional argument allows running trex on 10x Chromium data which have UMIs. Smartseq2 data don't have UMIs and for this purpose the `smartseq3` positional argument was added (the name of the argument is wrong and should be `smartseq2`). However, smartseq3 produces data with UMIs and there is currently no way to run trex on this. Therefore the following should be done:
* [x] `Smartseq3` positional argument renamed to `Smartseq2`
* [ ] help section/documentation updated on what it means to run trex with `Smartseq2` argument (no UMIs)
* [x] #13

**Comment by marcelm** [comment]
The `main` branch only has the `run10x` subcommand. Smart-Seq2 functionality is currently only in the `smartseq2` branch. Should that branch be merged?

**Comment by marcelm** [comment]
I’ve taken the liberty of editing your original post so that the items it contains are formatted as a to-do list.

**Comment by marcelm** [comment]
I have renamed the `smartseq3` branch to `smartseq2` and also added a commit to the branch that changes the subcommand name to `smartseq2`.

**Comment by marcelm** [comment]
I’ve converted the third item to a separate issue.

**Comment by Leonievb** [comment]
It would make sense to merge the smartseq2 branch into the main branch to make it easily available

**Comment by marcelm** [comment]
Ok, I’ll send an e-mail to confirm with Michael.

**Comment by marcelm** [comment]
I have merged the branch now. I would usually open a PR for something like this, but there were some merge conflicts that were a bit tricky to fix, so I just did the merge "by hand".
