### ISSUE TITLE
Issue reproducing Visium results

### ISSUE THREAD

**Issue by MDLDan** [frisen-lab/TREX#83]
Hi Team,

Thanks for the nice work.

I was trying to reproduce some of the analysis of your paper, particularly on the visium dataset, but I am struggling a bit.
For now I have only tried one slide (GSM4644079).

The challenges I am facing:
* After running spaceranger and inspecting the output bam file, I noticed some reads with downstream sequence = `CTTTAAGACCAATGACTTA` gets aligned to `chrH2B-EGFP-N` some don't. 
* As a result when running `trex run10x` it only finds 56 barcodes.
* Furthermore some barcodes are clearly a substring of others e.g.  `AGATTCTATAAACT----------------` `AGATTCTATAAACTGTGCGGTCACTCTCGT` 
* Lastly both aligned and unaligned reads shows `TTCTATAAACTGTGCGG` as constant region upstream the 30bp of the barcode. whereas in your reference you have `CAAGTAAATGCA`

Additionally if I run trex with auto detection it raises:
```
line 274, in detect_clone_id_location
    raise ValueError(
ValueError: Could not detect cloneID location on chromosome chrH2B-EGFP-N
```

Right now I am running with
`trex run10x slide1bam/ --visium -o trex_output_2/  --start 1122 --end 1151` according to #1 
Bam file used for trex using `spaceranger 3.0.0`

Could you clarify the expected upstream and downstream constants of the construct, and if the reference in the GitHub folder is the right one to use?

Any help is appreciated. Thank you.

**Comment by marcelm** [comment]
Hi, thanks for trying this out! I was not the person who ran those experiments, so I cannot authoritatively say what is going on, but I have access to the original files and will write down here what I found out.

I hope @Leonievb can maybe chime in.

In short, I believe chrH2B-EGFP-N is not the correct reference to use.

The [GSM4644079](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4644079) library you’re looking at was called "V9" in our analyses. (This can only be seen by the filename `GSM4644079_v9_filtered_gene_bc_matrix_spatial.tar.gz`, which contains `_v9_`.)

According to [Supplementary Table 4](https://static-content.springer.com/esm/art%3A10.1038%2Fs41593-022-01011-x/MediaObjects/41593_2022_1011_MOESM6_ESM.xlsx), this is one of the "Spatial transcriptomics - Gene expression libraries" (sheet "spatial_gene_exp").

In the log files I found, all V* libraries (V9-V16) contain very few reads covering the cloneID (hundreds). Many more reads covering the cloneID can be found in the targeted sequencing libraries. According to the "Spatial transcriptomics - cloneID amplicon libraries" table (sheet "spatial_cloneID"), the library corresponding to V9 would be "amp56". This is [GEO library GSM4644087](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4644087).

Also, according to the log files, the reference that was used was *not* "chrH2B-EGFP-N", and also different `--start` and `--end` parameters were used. I will need to get back to you regarding the reference.

> * Furthermore some barcodes are clearly a substring of others e.g.  `AGATTCTATAAACT----------------` `AGATTCTATAAACTGTGCGGTCACTCTCGT`

TREX recognizes this and will 1) correct truncated cloneIDs and 2) filter too short cloneIDs.

In `reads.txt` and `molecules.txt`, the correction hasn’t been done, so it is normal to see these short cloneIDs. In `molecules_corrected.txt`, the correction was done and when you compare the `original_clone_id` and `clone_id` column, you should see this happening. Some cloneIDs will still appear truncated, and for those, we err on the side of caution and filter them out when grouping the molecules into cells, so usually you should not see them in `cells.txt` anymore.

**Comment by MDLDan** [comment]
Thanks for the comprehensive reply @marcelm. I totally missed there were targeted reseq files.

@Leonievb I would really appreciate some guidance on how to run TREX on the visium targeted seq slides.

**Comment by MDLDan** [comment]
Small update, I downloaded the targeted reseq but it seems both read 1 and read 2 are into 1 fastq file If downloaded from SRA or ENA. `--split-files` or `--split-3` from `sra_toolkit` won't work.

This seems to be confirmed by checking the ENA browser as well.
E.g. https://www.ebi.ac.uk/ena/browser/view/SRX8627803

From the SRA explorer I can see originally R1 and R2 files were submitted.

**Comment by marcelm** [comment]
I can confirm your observation, but cannot find the original files.

> From the SRA explorer I can see originally R1 and R2 files were submitted.

Do you have a link? I don’t see that.

**Comment by MDLDan** [comment]
Sure. As an example for SRR12103552 slide_v9 reseq.
If you go to the data access page of the SRA explorer
https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR12103552&display=data-access


You can see the R1 and R2 files in the **Original format** section.

**Comment by marcelm** [comment]
Michael Ratz sent me the virus sequence used for the Visium libraries. I have added it to the repository; the file is https://github.com/frisen-lab/TREX/blob/main/references/pMR526_LV-EF1a-H2B-EGFP-BC.fa. See also the new [Visium section](https://github.com/frisen-lab/TREX/blob/main/README.md#visium) I added to the README.

**Comment by marcelm** [comment]
I can confirm your trouble getting the files for SRR12103552. When I ran `fastq-dump --split-files SRR12103552`, I actually get `SRR12103552_1.fastq` and `SRR12103552_2.fastq`, where the reads in the first have 28 nt and the ones in the second 120 nt. However, the two files have a different number of records and the record ids don’t match up so there’s no way to recover the correct pairing it seems (`--split-3` did not work).

I’ve never used AWS, but maybe trying to retrieve the files from S3 would work? I attempted to convert the URL to https and use https://sra-pub-src-9.s3.amazonaws.com/SRR12103552/amp56_S5_L003_R1_001.fastq.gz.1, but I get access denied. In the table, it says "Use Cloud Data Delivery" under the "Access type" column, so maybe one could get the data that way.

**Comment by MDLDan** [comment]
I noticed the read names are named sequentially in the SRA conversion but there is the same number of reads with lengths 28 and 120. I would attempt to rename the 120 bp reads to match the 28 nt if that won't work I will look into aws and the cloud delivery service.
I consider the issue closed. Thank you @marcelm for your help.

**Comment by marcelm** [comment]
Great, I’m glad we could help. Will close the issue, but feel free to comment here if there’s anything else.
